### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by arabian9ts** [arabian9ts/GroupMorning#19]
* Integrate DropDownQueue framework
* add travis file

**Comment by Kansei** [comment]
- [ ] errorの改善 #20
- [ ] sent UDID
- [ ]  通知の処理(起こす相手や起こし方などの情報をjsonでrailsに送り、railsから起こす端末にjsonデータを送る)
- [ ] herokuの設定

**Comment by ellieny** [comment]
- [] add alarm view & controller
- [] NotificationCenterを設定時間に通知
- [] スライダー/ボタンがoffになったら元の画面に戻る
- [] AppDelegateをObserverにして、AppDelegate内でexeSegue()を呼びだして、画面遷移行う
